# Generated by Django 3.0.8 on 2020-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=20)),
                ('entry', models.TextField(help_text='entry', max_length=20)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
